SELECT 
	LS_MASTER.ID AS 'Contract ID',
	UATB_SC_CUST_NAME AS 'Customer Name',
	UATB_SC_ACTIV_DATE AS 'Date Commenced',
	CONTRACT_TERM AS 'Contract Term',
	TERM_DATE AS 'Term Date',
	UATB_JS_TOT_SERV_AT_COMMENCEMT AS 'Total Service',
	UATB_SC_TODAY AS "Today's Date",
	UATB_JS_EQUIP_CITY AS 'Equip. City',
	UATB_JS_EQUIP_STATE AS 'Equip. State',
	UATB_SC_MRKTNG_REP2_DESC AS 'Equip. Rep',
	UATB_JS_CCAN_SOLDTO  AS 'SoldTo',
	BOOKING_DATE
	
FROM 
	LS_MASTER_RPTS_NF LS_MASTER,  
	CS_MASTER_NF CS_MASTER 
WHERE 
	LS_MASTER.CUST_CREDIT_ACCT = CS_MASTER.ID
	AND ( PROMOTION <> '31'
	AND UATB_JS_SERVICE_ON_LEASE = 'YES'
	AND BOOKING_DATE >= ? AND BOOKING_DATE <= ? )