SELECT DISTINCT  
	CR_ATTG_NAME,
	UATB_JS_ASSET_VENDOR_NAME,
	AS_MASTER.ID,
	CONTRACT_NO,
	CUST_CREDIT_ACCT,
	UATB_SC_CUST_NAME,
	CUST_ID,
	CD_STATE,
	EQUIP_LIST_PRICE,
	A_SYSTEM_DATE,
	EQUIP_DESC,
	MODEL,
	SERIAL_NUMBER,
	QUANTITY,
	EQUIP_COST,
	A_ORIG_COST,
	RESID_AMT,
	UATB_JS_TRADE_IN_AMT,
	UATB_SC_AUM_ALPHA_NUM2,
EQUIP_CITY,
	EQUIP_STATE,
	PYMTS_ARREARS,
	EQUIP_ADDR1,
	EQUIP_ADDR2 
FROM 
	AS_MASTER_RPTS_NF AS_MASTER,  
	LS_MASTER_RPTS_NF LS_MASTER,  
	CS_DEFAULTS_NF CS_DEFAULT,  
	LS_BILLING_NF LS_BILLING,  
	AS_MASTER_RPTS_A_LOCATIONS AS_MASTER_,  
	AS_LOCATION_NF AS_LOCATION 
WHERE 
	AS_MASTER.CONTRACT_NO = LS_MASTER.ID
	AND LS_MASTER.CUST_CREDIT_ACCT = CS_DEFAULT.ID
	AND LS_MASTER.ID = LS_BILLING.ID
	AND AS_MASTER.ID = AS_MASTER_.ID
	AND AS_MASTER_.A_LOCATIONS = AS_LOCATION.ID
	AND ( ( CUST_ID IN( '0017648-001' ))
	AND UATB_SC_NUM_OF_ASSETS <> 0)
