SELECT 
	AS_MASTER.ID,
	CONTRACT_NO,
	UATB_SC_CUST_NAME,
	LS_MASTER.UATB_SC_ACTIV_DATE,
	CONTRACT_TERM,
	TERM_DATE,
	UATB_JS_EQUIP_CITY,
	UATB_JS_EQUIP_STATE,
	QUANTITY,
	MODEL,
	SERIAL_NUMBER,
	A_RENTAL_AMT,
	EQUIP_COST_PCT,
	MISC_AMT 
FROM 
	AS_MASTER_RPTS_NF AS_MASTER,  
	LS_MASTER_RPTS_NF LS_MASTER,  
	LS_MISC_REP_NF LS_MISC_REP 
WHERE 
	AS_MASTER.CONTRACT_NO = LS_MASTER.ID
	AND LS_MASTER.ID = LS_MISC_REP.MISC_CONTRACT_NO
	AND ( ( CONTRACT_NO = '101-0007328-054')
	AND MISC_GL_CODE = '0072') 