SELECT DISTINCT  
	APP_FKEY,
	CASE 
		WHEN AS_UD_AS_EQUIP_DESCRIP_TBDESC IN ( 'B/O', 'EUA' ) THEN AS_UD_AS_QUOTE_NUM 
		ELSE '' 
	END AS AS_UD_AS_QUOTE_NUM 
FROM 
	Rapport.dbo.RPT_CO RPT_CO,  
	Rapport.dbo.RPT_ASSET RPT_ASSET 
WHERE 
	RPT_CO.CO_KEY = RPT_ASSET.CO_FKEY
	AND ( ( APP_FKEY = ?)
	AND CASE 
		WHEN AS_UD_AS_EQUIP_DESCRIP_TBDESC IN ( 'B/O', 'EUA' ) THEN AS_UD_AS_QUOTE_NUM 
		ELSE '' 
	END IS NOT NULL) 