SELECT DISTINCT  
	CTS_APP_FKEY,
	CTS_CONTRACT_NUMBER,
	CO_UD_CO_CONTRACT_ID,
	CO_custName,
	CO_custState,
	CO_UD_CO_SERVICE_TOTAL,
	CO_termDuration,
	CO_branch_TBDESC,
	CO_UD_CO_SRV_QUOTE1,
	CO_UD_CO_SRV_QUOTE2,
	CO_UD_CO_SRV_QUOTE3,
	CO_programType_TBDESC,
	CO_UD_CO_MP_SERVICE,
	CO_UD_CO_SP_SERVICE,
	CO_UD_CO_GYRUS_SERVICE,
	CO_UD_CO_EW7_MAINT,
	cast(CO_commencementDate as DATE),
	cast(CO_terminationDate as DATE),
	AS_assetState_TBDESC,
	CO_promotion_TBDESC,
	cast(RPT_CO.CO_bookingDate as DATE)
	 
FROM 
	CONTRACT_SETUP CONTRACT_S_1,  
	RPT_CO RPT_CO,  
	DECISION_CODE_HISTORY DECISION_C,  
	RPT_ASSET RPT_ASSET 
WHERE 
	CONTRACT_S_1.CTS_CONTRACT_SETUP_KEY = RPT_CO.SETUP_FKEY
	AND CONTRACT_S_1.CTS_CONTRACT_SETUP_KEY = DECISION_C.DCH_SETUP_FKEY
	AND RPT_CO.CO_KEY = RPT_ASSET.CO_FKEY
	AND ( ( CO_UD_CO_SRV_QUOTE1 IS NOT NULL
	OR CO_UD_CO_SRV_QUOTE2 IS NOT NULL
	OR CO_UD_CO_SRV_QUOTE3 IS NOT NULL)
	AND CO_programType_TBDESC <> 'RENTAL AGREEMENTS'
	AND ( CO_promotion <> '31'
	OR CO_promotion IS NULL)
	AND APP_DECISION_CODE IN( 7, 8 )
	AND CAST( ( rtrim( cast( MONTH( DECISION_CODE_DATE ) 
AS char( 2 ) ) ) + '/' + rtrim( cast( DAY( DECISION_CODE_DATE ) AS char( 2 ) ) ) + '/' + cast( YEAR( DECISION_CODE_DATE )  AS char( 4 ) ) ) as DATE ) between ? AND ? ) 