SELECT DISTINCT  
	ID,
	UATB_SC_CUST_NAME,
	CUST_ID,
	LEAD_BANK,
	PRODUCT_LINE,
	CONTRACT_TERM,
	UATB_SC_UM_ALPHA_FIELD5,
	UATB_SC_UM_ALPHA_FIELD6,
	UATB_SC_UM_USER_AMT4,
	UATB_SC_ACTIV_DATE,
	TERM_DATE,
	UATB_SC_BRANCH,
	UATB_SC_MRKTNG_REP2_DESC,
	UATB_SC_MRKTNG_REP3_DESC,
	UATB_SC_AU_FIXED_READ,
	UATB_SC_CPP_TERM_CALC3A,
	UATB_SC_CPP_TERM_CALC3B,
	UATB_GET_CURRENT_RATE,
	UATB_CUR_SERVICE_RATE,
	UATB_GET_CURRENT_OTHER_RATE,
	UATB_SC_CONTRACT_PYTM,
	UATB_JS_CONTRACT_PUR_OP_DESC 
FROM 
	LS_MASTER_RPTS_NF LS_MASTER 
WHERE 
	( ( ( ( UATB_SC_LESSOR IN( '001', '002', '004', '005', '011', '012', '014', '015', '101', '102' )
	AND LEAD_BANK NOT LIKE '%100%')))
	AND PROGRAM_TYPE NOT IN( '8' ))
	AND ( UATB_SC_NUM_OF_ASSETS > 0
	AND UATB_SC_INVOICE_CODE NOT IN( 'N' )) 
ORDER BY 
	2