SELECT  [ContractID]
      ,[AS_UD_ORIG_ID]
      ,[AS_UD_SAP_INV_NUM]
      ,[AS_UD_SAP_INV_DATE]
      ,[AS_UD_LEAD_BANK]
      ,[AS_UD_DEPR_START_DATE]
      ,[AS_UD_DEPR_LIFE]
      ,[AS_UD_DEPR_BASIS]
      ,[AS_UD_DEPR_MONTH_AMT]
      ,[AS_UD_YTD_ACCUM_DEPR]
      ,[AS_UD_CTD_ACCUM_DEPR]
      ,[AS_UD_STATUS]
      ,[AS_UD_STATUS_DATE]
  FROM [RollOverTest].[dbo].[RollOverTest1]